# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/
!cat /content/drive/MyDrive/database1/data.yaml

# Commented out IPython magic to ensure Python compatibility.
import os

# %cd /content/drive/MyDrive/code_colab

!pip install pytorch_wavelets==1.3.0

# YOLO11n Baseline (200 Epochs)

from ultralytics import YOLO
import torch
import warnings
warnings.filterwarnings('ignore')

model_type = "yolo11n.pt"

data_yaml_path = "/content/drive/MyDrive/database1/data.yaml"

if __name__ == '__main__':

    model = YOLO(model_type)

    results = model.train(
        data=data_yaml_path,
        epochs=200,
        imgsz=640,
        batch=16,
        patience=30,
        device=0,
        project="/content/drive/MyDrive/InsPLAD_det_YOLOv11",
        name="yolo11n_baseline_official_2",
        exist_ok=True,
        cache="disk",
        plots=True,
        save=True
    )

# yolo11n + GatedAttention(e200)
from ultralytics import YOLO
import torch
import warnings
warnings.filterwarnings('ignore')

model_yaml_path ="/content/drive/MyDrive/code_colab/ultralytics/cfg/models/addv11/yolov11n_GatedAttention.yaml"

data_yaml_path = "/content/drive/MyDrive/database1/data.yaml"
if __name__ == '__main__':
    model = YOLO(model_yaml_path)
    model = model

results = model.train(
    data=data_yaml_path,
    epochs=200,
    imgsz=640,
    batch=16,
    patience=30,
    device=0,
    project="/content/drive/MyDrive/InsPLAD_det_YOLOv11",
    name="yolo11n_gatedattention_v1",
    exist_ok=True,
    amp=True,
    cache="disk",
    plots=True
)

# YOLO11n + p2-SimAM(200 Epochs)
from ultralytics import YOLO
import torch
import warnings
warnings.filterwarnings('ignore')

model_yaml_path ="/content/drive/MyDrive/code_colab_2/ultralytics/cfg/models/addv11/YOLO11_P2_SimAM.yaml"

data_yaml_path = "/content/drive/MyDrive/database1/data.yaml"
if __name__ == '__main__':
    model = YOLO(model_yaml_path)
    model = model

    results = model.train(
        data=data_yaml_path,
        epochs=200,
        imgsz=640,
        batch=16,
        patience=30,
        device=0,
        project="/content/drive/MyDrive/InsPLAD_det_YOLOv11",
        name="yolo11n_p2_SimAM_exp1",
        exist_ok=True,
        amp=True,
        cache="disk",
        plots=True,
        overlap_mask=True,
        mosaic=1.0,
        cls=1.0
    )

#YOLO11n+P2(200 Epochs)
from ultralytics import YOLO
import torch
import warnings
warnings.filterwarnings('ignore')

pretrained_weights = "yolo11n.pt"
model_yaml_path = "/content/drive/MyDrive/code_colab/ultralytics/cfg/models/addv11/yolo11n_p2.yaml"
data_yaml_path = "/content/drive/MyDrive/database1/data.yaml"

if __name__ == '__main__':

    base_model = YOLO(pretrained_weights)

    model = YOLO(model_yaml_path).load(pretrained_weights)
    print(f"model：{model_yaml_path}")

    results = model.train(
        data=data_yaml_path,
        epochs=200,
        imgsz=640,
        batch=16,
        patience=30,
        device=0,
        project="/content/drive/MyDrive/InsPLAD_det_YOLOv11",
        name="yolo11n_p2_transfer_SUCCESS",
        exist_ok=True,
        amp=True,
        cache="disk",
        close_mosaic=15,
        plots=True,
        pretrained=True
    )

# YOLO11n+P2+EMA(200 Epochs)

from ultralytics import YOLO
import torch
import warnings
warnings.filterwarnings('ignore')

pretrained_weights = "yolo11n.pt"
model_yaml_path = "/content/drive/MyDrive/code_colab_2/ultralytics/cfg/models/addv11/yolo11n_p2_EMA.yaml"
data_yaml_path = "/content/drive/MyDrive/database1/data.yaml"

if __name__ == '__main__':
    model = YOLO(model_yaml_path)
    model = model

    results = model.train(
        data=data_yaml_path,
        epochs=200,
        imgsz=640,
        batch=16,
        patience=30,
        device=0,
        project="/content/drive/MyDrive/InsPLAD_det_YOLOv11",
        name="yolo11n_ema_transfer_SUCCESS",
        exist_ok=True,
        amp=True,
        cache="disk",
        close_mosaic=15,
        plots=True,
        pretrained=True
    )

# YOLO11n+P2+EMA(200 Epochs)
# Add pre-trained weights from the original model
from ultralytics import YOLO
import torch
import warnings
warnings.filterwarnings('ignore')

pretrained_weights = "yolo11n.pt"
model_yaml_path = "/content/drive/MyDrive/code_colab_2/ultralytics/cfg/models/addv11/yolo11n_p2_EMA.yaml"
data_yaml_path = "/content/drive/MyDrive/database1/data.yaml"


if __name__ == '__main__':

    # First, initialize with the official model to ensure it has pre-trained weights.
    base_model = YOLO(pretrained_weights)

    model = YOLO(model_yaml_path).load(pretrained_weights)

    print(f"model：{model_yaml_path}")

    results = model.train(
        data=data_yaml_path,
        epochs=200,
        imgsz=640,
        batch=16,
        patience=30,
        device=0,
        project="/content/drive/MyDrive/InsPLAD_det_YOLOv11",
        name="yolo11n_ema_transfer_SUCCESS_2",
        exist_ok=True,
        amp=True,
        cache="disk",
        close_mosaic=15,
        plots=True,

        pretrained=True
    )