# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/
!cat /content/drive/MyDrive/database1/data.yaml

# Commented out IPython magic to ensure Python compatibility.
import os

# %cd /content/drive/MyDrive

!pip install pytorch_wavelets==1.3.0

!cp -r /content/drive/MyDrive/database2 /content/local_dataset

# ==========================================
# Complete InsPLAD fault classification training and visualization script
# ==========================================

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, models, transforms
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_fscore_support
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
import random
from tqdm import tqdm
from PIL import Image

# ================= 1. Configuration and Environment Setup =================

DATA_DIR = '/content/local_dataset'
SAVE_DIR = '/content/drive/MyDrive/InsPLAD_Stage2_Results_improved'
os.makedirs(SAVE_DIR, exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using Device: {DEVICE}")

# Hyperparameters
BATCH_SIZE = 32
EPOCHS = 30
LEARNING_RATE = 1e-4

# ================= 2. Data Augmentation and Loading =================

data_transforms = {
    'train': transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomRotation(15),
        transforms.ColorJitter(brightness=0.2, contrast=0.2),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'valid': transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

print("Loading datasets...")
# Check if the data exists
if not os.path.exists(DATA_DIR):
    raise FileNotFoundError(f"Dataset not found at {DATA_DIR}. Please check your path.")

image_datasets = {x: datasets.ImageFolder(os.path.join(DATA_DIR, x), data_transforms[x])
                  for x in ['train', 'valid']}

dataloaders = {x: DataLoader(image_datasets[x], batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
               for x in ['train', 'valid']}

class_names = image_datasets['train'].classes
dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'valid']}

# --- Calculate category weights ---
targets = np.array(image_datasets['train'].targets)
class_counts = np.bincount(targets)
weights = 1. / (torch.tensor(class_counts, dtype=torch.float) + 1e-6)
class_weights = (weights / weights.sum() * len(class_names)).to(DEVICE)

# ================= 3. Model Building =================

print("Initializing ResNet50...")
model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, len(class_names))
model = model.to(DEVICE)

criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE)

# ================= 4. Auxiliary Visualization Functions =================

def imshow_tensor(inp, title=None, ax=None, color='black'):
    inp = inp.cpu().numpy().transpose((1, 2, 0))
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    inp = std * inp + mean
    inp = np.clip(inp, 0, 1)

    if ax is None:
        plt.imshow(inp)
        if title: plt.title(title, color=color)
    else:
        ax.imshow(inp)
        if title: ax.set_title(title, color=color, fontsize=9, fontweight='bold')
        ax.axis('off')

def plot_training_curves(history):
    epochs_range = range(1, len(history['train_loss']) + 1)
    plt.figure(figsize=(14, 5))

    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, history['train_loss'], label='Train', color='#e74c3c', marker='o', markersize=4)
    plt.plot(epochs_range, history['val_loss'], label='Val', color='#3498db', marker='s', markersize=4)
    plt.title('Loss Convergence Analysis', fontsize=14)
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, history['train_acc'], label='Train', color='#e74c3c', marker='o', markersize=4)
    plt.plot(epochs_range, history['val_acc'], label='Val', color='#3498db', marker='s', markersize=4)
    plt.title('Accuracy Performance Curve', fontsize=14)
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(SAVE_DIR, '01_training_curves.png'), dpi=300)
    plt.show()

def visualize_predictions(model, loader, num_images=12):
    was_training = model.training
    model.eval()
    images_so_far = 0

    cols = 4
    rows = int(np.ceil(num_images / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(15, 3.5*rows))
    axes = axes.flatten()

    with torch.no_grad():
        for inputs, labels in loader:
            inputs = inputs.to(DEVICE)
            labels = labels.to(DEVICE)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            for j in range(inputs.size(0)):
                if images_so_far >= num_images: break

                ax = axes[images_so_far]
                is_correct = (preds[j] == labels[j])
                color = 'green' if is_correct else 'red'
                title = f"P: {class_names[preds[j]]}\nT: {class_names[labels[j]]}"

                imshow_tensor(inputs[j], title=title, ax=ax, color=color)
                images_so_far += 1

            if images_so_far >= num_images: break

    for k in range(images_so_far, len(axes)): axes[k].axis('off')

    plt.tight_layout()
    plt.savefig(os.path.join(SAVE_DIR, '02_predictions_sample.png'), dpi=300)
    plt.show()
    model.train(mode=was_training)

def visualize_errors(model, loader, num_images=8):

    model.eval()
    error_imgs, error_lbls, error_preds = [], [], []

    with torch.no_grad():
        for inputs, labels in loader:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)


            wrong_idx = (preds != labels).nonzero(as_tuple=True)[0]
            for idx in wrong_idx:
                if len(error_imgs) < num_images:
                    error_imgs.append(inputs[idx].cpu())
                    error_lbls.append(labels[idx].cpu().item())
                    error_preds.append(preds[idx].cpu().item())
                else: break
            if len(error_imgs) >= num_images: break

    if not error_imgs:
        print("Perfect! No errors found to visualize.")
        return

    cols = 4
    rows = int(np.ceil(len(error_imgs) / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(15, 3.5*rows))
    axes = axes.flatten() if isinstance(axes, np.ndarray) else [axes]

    for i in range(len(error_imgs)):
        title = f"True: {class_names[error_lbls[i]]}\nPred: {class_names[error_preds[i]]}"
        imshow_tensor(error_imgs[i], title=title, ax=axes[i], color='red')

    for k in range(len(error_imgs), len(axes)): axes[k].axis('off')

    plt.suptitle("Error Analysis (Failure Cases)", fontsize=16)
    plt.tight_layout()
    plt.savefig(os.path.join(SAVE_DIR, '03_error_analysis.png'), dpi=300)
    plt.show()

# ================= 5. Training the main loop =================

def train_model():
    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}
    best_acc = 0.0

    for epoch in range(EPOCHS):
        model.train()
        running_loss, running_corrects = 0.0, 0

        pbar = tqdm(dataloaders['train'], desc=f"Epoch {epoch+1}/{EPOCHS}")
        for inputs, labels in pbar:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            _, preds = torch.max(outputs, 1)
            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)
            pbar.set_postfix(loss=loss.item())

        epoch_loss = running_loss / dataset_sizes['train']
        epoch_acc = running_corrects.double() / dataset_sizes['train']
        history['train_loss'].append(epoch_loss)
        history['train_acc'].append(epoch_acc.item())

        model.eval()
        val_loss_run, val_corrects = 0.0, 0
        with torch.no_grad():
            for inputs, labels in dataloaders['valid']:
                inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                _, preds = torch.max(outputs, 1)
                val_loss_run += loss.item() * inputs.size(0)
                val_corrects += torch.sum(preds == labels.data)

        val_loss = val_loss_run / dataset_sizes['valid']
        val_acc = val_corrects.double() / dataset_sizes['valid']
        history['val_loss'].append(val_loss)
        history['val_acc'].append(val_acc.item())

        print(f"Val Acc: {val_acc:.4f} (Best: {max(best_acc, val_acc):.4f})")

        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model.state_dict(), os.path.join(SAVE_DIR, 'best_model.pth'))

    return history

# ================= 6. Final evaluation entry point =================

if __name__ == '__main__':
    print("Starting Training Process...")
    history = train_model()

    print("\nLoading Best Model for Evaluation...")
    # Load the best model
    model.load_state_dict(torch.load(os.path.join(SAVE_DIR, 'best_model.pth')))
    model.eval()

    # Collect prediction data
    all_preds, all_labels = [], []
    with torch.no_grad():
        for inputs, labels in dataloaders['valid']:
            inputs = inputs.to(DEVICE)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.numpy())


    print("\nGenerating PPT Materials...")

    # 1. Training Curve
    plot_training_curves(history)

    # 2. Confusion Matrix
    plt.figure(figsize=(10, 8))
    sns.heatmap(confusion_matrix(all_labels, all_preds), annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names, cbar=False)
    plt.title('Confusion Matrix: Fault Diagnosis Result', fontsize=14)
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.savefig(os.path.join(SAVE_DIR, '05_confusion_matrix.png'), dpi=300)
    plt.show()

    # 3. Prediction Example Display
    visualize_predictions(model, dataloaders['valid'], num_images=12)

    # 4. Analysis of Error Notebook
    visualize_errors(model, dataloaders['valid'], num_images=8)

    # 5. Classification report text
    print("\nClassification Report:")
    report = classification_report(all_labels, all_preds, target_names=class_names)
    print(report)
    with open(os.path.join(SAVE_DIR, 'classification_report.txt'), 'w') as f:
        f.write(report)

    print(f"\nAll operations completed! Results are saved in: {SAVE_DIR}")

#part3:system merge

#Loading improved yolo11n with P2
import os
import torch
import cv2
import numpy as np
from PIL import Image
from tqdm import tqdm
import torch.nn as nn
from torchvision import models, transforms
from ultralytics import YOLO

# ================= 1. Configuration and Model Loading =================
detector = YOLO('/content/drive/MyDrive/InsPLAD_det_YOLOv11/yolo11n_p2_transfer_SUCCESS/weights/best.pt')

# Phase 2: ResNet Fault Classification
class_names = ['bird-nest', 'corrosao', 'good', 'missing-cap', 'normal', 'rust']
classifier = models.resnet50()
classifier.fc = nn.Linear(classifier.fc.in_features, len(class_names))
classifier.load_state_dict(torch.load('/content/drive/MyDrive/InsPLAD_Stage2_Results/best_fault_classifier.pth'))
classifier.eval().cuda()

# Image Preprocessing
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# ================= 2. Core Business Logic Mapping =================
ASSET_FAULT_LOGIC = {
    'glass insulator': ['missing-cap', 'good'],
    'lightning rod suspension': ['rust', 'good'],
    'polymer insulator upper shackle': ['corrosao', 'normal'],
    'vari-grip': ['bird-nest', 'good', 'rust'],
    'yoke suspension': ['good', 'rust']
}

SAVE_DIR = '/content/drive/MyDrive/e2e_verified_results_test_1'
os.makedirs(SAVE_DIR, exist_ok=True)

# ================= 3. End-to-end system-level statistical operation =================
def run_system_analytics(img_dir):
    # --- Statistical funnel indicators ---
    total_images_processed = 0
    total_assets_detected = 0      # Total assets detected by YOLO
    raw_faults_predicted = 0       # The number of times ResNet's original prediction was "sick".
    logic_corrections = 0          # Number of times intercepted and corrected by business logic
    final_validated_faults = 0     # The final output is the actual number of alarms.

    fault_summary = {name: 0 for name in class_names if name not in ['good', 'normal']}

    img_list = [f for f in os.listdir(img_dir) if f.endswith(('.jpg', '.png'))]

    for img_name in tqdm(img_list, desc="Running System Analytics"):
        img_path = os.path.join(img_dir, img_name)
        img = cv2.imread(img_path)
        if img is None: continue
        total_images_processed += 1
        canvas = img.copy()

        # 1. Target Detection Phase
        results = detector(img_path, conf=0.25, verbose=False)[0]
        has_final_fault = False

        for box in results.boxes:
            total_assets_detected += 1
            asset_cls = detector.names[int(box.cls[0])]
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            # 2. Fault Diagnosis Phase
            roi = img[y1:y2, x1:x2]
            if roi.size == 0: continue
            roi_pil = Image.fromarray(cv2.cvtColor(roi, cv2.COLOR_BGR2RGB))
            input_tensor = preprocess(roi_pil).unsqueeze(0).cuda()

            with torch.no_grad():
                pred_idx = torch.max(classifier(input_tensor), 1)[1].item()
                raw_label = class_names[pred_idx]

            # Record whether the original error was reported.
            if raw_label not in ['good', 'normal']:
                raw_faults_predicted += 1

            # 3. Business logic constraint layer
            allowed_labels = ASSET_FAULT_LOGIC.get(asset_cls, ['good', 'normal'])

            if raw_label in allowed_labels:
                final_label = raw_label
            else:
                final_label = 'good' if 'good' in allowed_labels else 'normal'

                if raw_label not in ['good', 'normal']:
                    logic_corrections += 1

            # 4. Statistical and Visualization Results
            if final_label not in ['good', 'normal']:
                final_validated_faults += 1
                fault_summary[final_label] += 1
                has_final_fault = True

                cv2.rectangle(canvas, (x1, y1), (x2, y2), (0, 0, 255), 3)
                cv2.putText(canvas, f"{asset_cls}:{final_label}", (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)


        if has_final_fault:
            cv2.imwrite(os.path.join(SAVE_DIR, f"sys_alert_{img_name}"), canvas)

    # ================= 4. Output a system-level analysis report. =================
    print("\n" + "="*60)
    print("🚀 Power Line Inspection System - Analytics Report 🚀")
    print("="*60)
    print(f"Images Processed          : {total_images_processed}")
    print(f"[Stage 1] Assets Detected : {total_assets_detected} (Boxes cropped to ResNet)")
    print(f"[Stage 2] Raw Faults Pred : {raw_faults_predicted} (Before logic filter)")
    print(f"[Stage 3] Logic Intercepts: {logic_corrections} (False alarms prevented)")
    print(f"[Output ] Final Validated Alerts: {final_validated_faults}")
    print("-" * 60)
    print("Breakdown of Validated Faults:")
    for fault, count in fault_summary.items():
        if count > 0:
            print(f"  - {fault:15}: {count}")
    print("="*60)

run_system_analytics('/content/drive/MyDrive/database1/test/images')

#Loading baseline yolo11n

import os
import torch
import cv2
import numpy as np
from PIL import Image
from tqdm import tqdm
import torch.nn as nn
from torchvision import models, transforms
from ultralytics import YOLO

# ================= 1. Configuration and Model Loading =================

detector = YOLO('/content/drive/MyDrive/InsPLAD_det_YOLOv11/yolo11n_baseline_official_2/weights/best.pt')

# Phase 2: ResNet Fault Classification
class_names = ['bird-nest', 'corrosao', 'good', 'missing-cap', 'normal', 'rust']
classifier = models.resnet50()
classifier.fc = nn.Linear(classifier.fc.in_features, len(class_names))
classifier.load_state_dict(torch.load('/content/drive/MyDrive/InsPLAD_Stage2_Results/best_fault_classifier.pth'))
classifier.eval().cuda()

# Image preprocessing
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# ================= 2. Core Business Logic Mapping =================
ASSET_FAULT_LOGIC = {
    'glass insulator': ['missing-cap', 'good'],
    'lightning rod suspension': ['rust', 'good'],
    'polymer insulator upper shackle': ['corrosao', 'normal'],
    'vari-grip': ['bird-nest', 'good', 'rust'],
    'yoke suspension': ['good', 'rust']
}

SAVE_DIR = '/content/drive/MyDrive/e2e_verified_results_test_3'
os.makedirs(SAVE_DIR, exist_ok=True)

# =================  =================
def run_system_analytics(img_dir):

    total_images_processed = 0
    total_assets_detected = 0
    raw_faults_predicted = 0
    logic_corrections = 0
    final_validated_faults = 0

    fault_summary = {name: 0 for name in class_names if name not in ['good', 'normal']}

    img_list = [f for f in os.listdir(img_dir) if f.endswith(('.jpg', '.png'))]

    for img_name in tqdm(img_list, desc="Running System Analytics"):
        img_path = os.path.join(img_dir, img_name)
        img = cv2.imread(img_path)
        if img is None: continue
        total_images_processed += 1
        canvas = img.copy()


        results = detector(img_path, conf=0.25, verbose=False)[0]
        has_final_fault = False

        for box in results.boxes:
            total_assets_detected += 1
            asset_cls = detector.names[int(box.cls[0])]
            x1, y1, x2, y2 = map(int, box.xyxy[0])


            roi = img[y1:y2, x1:x2]
            if roi.size == 0: continue
            roi_pil = Image.fromarray(cv2.cvtColor(roi, cv2.COLOR_BGR2RGB))
            input_tensor = preprocess(roi_pil).unsqueeze(0).cuda()

            with torch.no_grad():
                pred_idx = torch.max(classifier(input_tensor), 1)[1].item()
                raw_label = class_names[pred_idx]


            if raw_label not in ['good', 'normal']:
                raw_faults_predicted += 1

            allowed_labels = ASSET_FAULT_LOGIC.get(asset_cls, ['good', 'normal'])

            if raw_label in allowed_labels:
                final_label = raw_label
            else:
                final_label = 'good' if 'good' in allowed_labels else 'normal'

                if raw_label not in ['good', 'normal']:
                    logic_corrections += 1


            if final_label not in ['good', 'normal']:
                final_validated_faults += 1
                fault_summary[final_label] += 1
                has_final_fault = True

                cv2.rectangle(canvas, (x1, y1), (x2, y2), (0, 0, 255), 3)
                cv2.putText(canvas, f"{asset_cls}:{final_label}", (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)


        if has_final_fault:
            cv2.imwrite(os.path.join(SAVE_DIR, f"sys_alert_{img_name}"), canvas)

    print("\n" + "="*60)
    print("🚀 Power Line Inspection System - Analytics Report 🚀")
    print("="*60)
    print(f"Images Processed          : {total_images_processed}")
    print(f"[Stage 1] Assets Detected : {total_assets_detected} (Boxes cropped to ResNet)")
    print(f"[Stage 2] Raw Faults Pred : {raw_faults_predicted} (Before logic filter)")
    print(f"[Stage 3] Logic Intercepts: {logic_corrections} (False alarms prevented)")
    print(f"[Output ] Final Validated Alerts: {final_validated_faults}")
    print("-" * 60)
    print("Breakdown of Validated Faults:")
    for fault, count in fault_summary.items():
        if count > 0:
            print(f"  - {fault:15}: {count}")
    print("="*60)

run_system_analytics('/content/drive/MyDrive/database1/test/images')

#Loading improved yolo11n with P2&EMA
import os
import torch
import cv2
import numpy as np
from PIL import Image
from tqdm import tqdm
import torch.nn as nn
from torchvision import models, transforms
from ultralytics import YOLO

detector = YOLO('/content/drive/MyDrive/InsPLAD_det_YOLOv11/yolo11n_ema_transfer_SUCCESS/weights/best.pt')

class_names = ['bird-nest', 'corrosao', 'good', 'missing-cap', 'normal', 'rust']
classifier = models.resnet50()
classifier.fc = nn.Linear(classifier.fc.in_features, len(class_names))
classifier.load_state_dict(torch.load('/content/drive/MyDrive/InsPLAD_Stage2_Results/best_fault_classifier.pth'))
classifier.eval().cuda()

preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

ASSET_FAULT_LOGIC = {
    'glass insulator': ['missing-cap', 'good'],
    'lightning rod suspension': ['rust', 'good'],
    'polymer insulator upper shackle': ['corrosao', 'normal'],
    'vari-grip': ['bird-nest', 'good', 'rust'],
    'yoke suspension': ['good', 'rust']
}

SAVE_DIR = '/content/drive/MyDrive/e2e_verified_results_test_2'
os.makedirs(SAVE_DIR, exist_ok=True)

def run_system_analytics(img_dir):

    total_images_processed = 0
    total_assets_detected = 0
    raw_faults_predicted = 0
    logic_corrections = 0
    final_validated_faults = 0

    fault_summary = {name: 0 for name in class_names if name not in ['good', 'normal']}

    img_list = [f for f in os.listdir(img_dir) if f.endswith(('.jpg', '.png'))]

    for img_name in tqdm(img_list, desc="Running System Analytics"):
        img_path = os.path.join(img_dir, img_name)
        img = cv2.imread(img_path)
        if img is None: continue
        total_images_processed += 1
        canvas = img.copy()

        results = detector(img_path, conf=0.25, verbose=False)[0]
        has_final_fault = False

        for box in results.boxes:
            total_assets_detected += 1
            asset_cls = detector.names[int(box.cls[0])]
            x1, y1, x2, y2 = map(int, box.xyxy[0])


            roi = img[y1:y2, x1:x2]
            if roi.size == 0: continue
            roi_pil = Image.fromarray(cv2.cvtColor(roi, cv2.COLOR_BGR2RGB))
            input_tensor = preprocess(roi_pil).unsqueeze(0).cuda()

            with torch.no_grad():
                pred_idx = torch.max(classifier(input_tensor), 1)[1].item()
                raw_label = class_names[pred_idx]


            if raw_label not in ['good', 'normal']:
                raw_faults_predicted += 1


            allowed_labels = ASSET_FAULT_LOGIC.get(asset_cls, ['good', 'normal'])

            if raw_label in allowed_labels:
                final_label = raw_label
            else:
                final_label = 'good' if 'good' in allowed_labels else 'normal'

                if raw_label not in ['good', 'normal']:
                    logic_corrections += 1


            if final_label not in ['good', 'normal']:
                final_validated_faults += 1
                fault_summary[final_label] += 1
                has_final_fault = True

                cv2.rectangle(canvas, (x1, y1), (x2, y2), (0, 0, 255), 3)
                cv2.putText(canvas, f"{asset_cls}:{final_label}", (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)


        if has_final_fault:
            cv2.imwrite(os.path.join(SAVE_DIR, f"sys_alert_{img_name}"), canvas)


    print("\n" + "="*60)
    print("🚀 Power Line Inspection System - Analytics Report 🚀")
    print("="*60)
    print(f"Images Processed          : {total_images_processed}")
    print(f"[Stage 1] Assets Detected : {total_assets_detected} (Boxes cropped to ResNet)")
    print(f"[Stage 2] Raw Faults Pred : {raw_faults_predicted} (Before logic filter)")
    print(f"[Stage 3] Logic Intercepts: {logic_corrections} (False alarms prevented)")
    print(f"[Output ] Final Validated Alerts: {final_validated_faults}")
    print("-" * 60)
    print("Breakdown of Validated Faults:")
    for fault, count in fault_summary.items():
        if count > 0:
            print(f"  - {fault:15}: {count}")
    print("="*60)

run_system_analytics('/content/drive/MyDrive/database1/test/images')